services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-wikipedia_crawler}
    volumes:
      - ./db/create.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB:-wikipedia_crawler}"]
      interval: 5s
      timeout: 60s
      retries: 5
  
  agent:
    build:
      context: .
      dockerfile: dockerfile
    environment:
      - DB_HOST=${POSTGRES_HOST:-postgres}
      - DB_PORT=${POSTGRES_PORT:-5432}
      - DB_NAME=${POSTGRES_DB:-wikipedia_crawler}
      - DB_USER=${POSTGRES_USER:-user}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-password}
    restart: unless-stopped

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      device: ./volumes/pgdata
      o: bind
